apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: <your-prefix>.azurecr.io/worker:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: "StorageConnectionString"
            value: "<your connection string>"
          - name: "HubProcessUrl"
            value: "http://web/process"